import type { NextPage } from 'next'
import Head from 'next/head'
import Board from '../containers/Board'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tic Tac Toe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&family=Secular+One&family=Staatliches&display=swap" rel="stylesheet" />
      </Head>
      <main><Board /></main>

    </div>
  )
}

export default Home
